name: Setup AWS Credentials
description: Configure AWS credentials for CloudFormation deployment
inputs:
  aws-role-arn:
    description: 'AWS role ARN to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: ${{ github.job }}