name: Deploy to Dev Environment

on:
  workflow_call: # Allows reuse of workflow by other workflows i.e main.yml

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN_DEV }}
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-vpc:
    name: Deploy VPC Layer
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Deploy VPC Stack
        uses: ./.github/actions/deploy-cloudformation
        with:
          stack-type: vpc
          template-path: templates/vpc.yaml
          parameters-path: parameters/dev/vpc-parameters.json
          aws-role-arn: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

  deploy-alb:
    name: Deploy ALB Layer
    runs-on: ubuntu-latest
    needs: deploy-vpc
    environment: development
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Deploy ALB Stack
        uses: ./.github/actions/deploy-cloudformation
        with:
          stack-type: alb
          template-path: templates/alb.yaml
          parameters-path: parameters/dev/alb-parameters.json
          aws-role-arn: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

  deploy-app:
    name: Deploy App Layer
    runs-on: ubuntu-latest
    needs: deploy-alb
    environment: development
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Deploy App Stack
        uses: ./.github/actions/deploy-cloudformation
        with:
          stack-type: app
          template-path: templates/app.yaml
          parameters-path: parameters/dev/app-parameters.json
          aws-role-arn: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

  deploy-db:
    name: Deploy Database Layer
    runs-on: ubuntu-latest
    needs: deploy-app
    environment: development
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Deploy DB Stack
        uses: ./.github/actions/deploy-cloudformation
        with:
          stack-type: db
          template-path: templates/db.yaml
          parameters-path: parameters/dev/db-parameters.json
          aws-role-arn: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}