name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
      - 'parameters/**'
      - '.github/workflows/**'
  workflow_dispatch: # Facilitates Manual trigger in UI for emergency deployments/testing purpose

permissions:
  id-token: write
  contents: read

jobs:
  lint-and-scan:
    name: Lint & Scan
    uses: ./.github/workflows/lint-and-scan.yml
    permissions:
      security-events: write
      contents: read #  When job-level permission is mentioned, it overrides the top-level permissions completely, hence adding this again

  deploy-dev:
    name: Deploy to Dev
    needs: lint-and-scan
    uses: ./.github/workflows/deploy-dev.yml
    secrets: inherit

  deploy-staging:
    name: Deploy to Staging
    needs: deploy-dev
    uses: ./.github/workflows/deploy-staging.yml
    secrets: inherit

  deploy-prod:
    name: Deploy to Production
    needs: deploy-staging
    uses: ./.github/workflows/deploy-prod.yml
    secrets: inherit