name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
      - 'parameters/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  lint-and-scan:
    name: Lint & Scan
    uses: ./.github/workflows/lint-and-scan.yml
    permissions:
      contents: read
      security-events: write

  deploy-dev:
    name: Deploy to Dev
    needs: lint-and-scan
    uses: ./.github/workflows/deploy-dev.yml
    secrets: inherit

  deploy-staging:
    name: Deploy to Staging
    needs: deploy-dev
    uses: ./.github/workflows/deploy-staging.yml
    secrets: inherit

  deploy-prod:
    name: Deploy to Production
    needs: deploy-staging
    uses: ./.github/workflows/deploy-prod.yml
    secrets: inherit